In [1]:
import pandas as pd

orders = {
    "Order_ID":[101,102,103,104,105,106,107,108,109,110],
    "Customer":["Alice","Bob","Charlie","David","Emma","Frank","Grace","Henry","Isabella","Jack"],
    "Category":["Electronics","Furniture","Electronics","Clothing","Furniture","Electronics","Clothing","Furniture","Electronics","Clothing"],
    "Sales":[1200,800,950,300,650,1500,400,700,1100,350],
    "Quantity":[2,1,2,3,1,2,4,1,2,3],
    "Discount":[5,10,None,0,15,5,0,None,10,5]
}

df = pd.DataFrame(orders)

df.to_csv("customer_orders.csv", index=False)

df.head()

   Order_ID Customer     Category  Sales  Quantity  Discount
0       101    Alice  Electronics   1200         2       5.0
1       102      Bob    Furniture    800         1      10.0
2       103  Charlie  Electronics    950         2       NaN
3       104    David     Clothing    300         3       0.0
4       105     Emma    Furniture    650         1      15.0

In [2]:
import pandas as pd

df = pd.read_csv("customer_orders.csv")

df.head()

   Order_ID Customer     Category  Sales  Quantity  Discount
0       101    Alice  Electronics   1200         2       5.0
1       102      Bob    Furniture    800         1      10.0
2       103  Charlie  Electronics    950         2       NaN
3       104    David     Clothing    300         3       0.0
4       105     Emma    Furniture    650         1      15.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  10 non-null     int64
 1   Customer  10 non-null     str
 2   Category  10 non-null     str
 3   Sales     10 non-null     int64
 4   Quantity  10 non-null     int64
 5   Discount  8 non-null      float64
dtypes: float64(1), int64(3), str(2)
memory usage: 612.0 bytes

In [4]:
df.describe()

        Order_ID        Sales   Quantity   Discount
count   10.00000    10.000000  10.000000   8.000000
mean   105.50000   795.000000   2.100000   6.250000
std      3.02765   395.425228   0.994429   5.175492
min    101.00000   300.000000   1.000000   0.000000
25%    103.25000   462.500000   1.250000   3.750000
50%    105.50000   750.000000   2.000000   5.000000
75%    107.75000  1062.500000   2.750000  10.000000
max    110.00000  1500.000000   4.000000  15.000000

In [5]:
df.isnull().sum()

Order_ID    0
Customer    0
Category    0
Sales       0
Quantity    0
Discount    2
dtype: int64

In [6]:
df["Discount"] = df["Discount"].fillna(0)

df.isnull().sum()

Order_ID    0
Customer    0
Category    0
Sales       0
Quantity    0
Discount    0
dtype: int64

In [7]:
df["Final_Sales"] = df["Sales"] - (df["Sales"] * df["Discount"] / 100)

df.head()

   Order_ID Customer     Category  Sales  Quantity  Discount  Final_Sales
0       101    Alice  Electronics   1200         2       5.0       1140.0
1       102      Bob    Furniture    800         1      10.0        720.0
2       103  Charlie  Electronics    950         2       0.0        950.0
3       104    David     Clothing    300         3       0.0        300.0
4       105     Emma    Furniture    650         1      15.0        552.5

In [8]:
df["Final_Sales"].sum()

np.float64(7510.0)

In [9]:
df["Final_Sales"].mean()

np.float64(751.0)

In [10]:
df.loc[df["Final_Sales"].idxmax()]

Order_ID               106
Customer             Frank
Category       Electronics
Sales                 1500
Quantity                 2
Discount               5.0
Final_Sales         1425.0
Name: 5, dtype: object

In [11]:
df.loc[df["Final_Sales"].idxmin()]

Order_ID            104
Customer          David
Category       Clothing
Sales               300
Quantity              3
Discount            0.0
Final_Sales       300.0
Name: 3, dtype: object

In [12]:
df.groupby("Category")["Final_Sales"].sum()

Category
Clothing       1032.5
Electronics    4505.0
Furniture      1972.5
Name: Final_Sales, dtype: float64

In [13]:
df.groupby("Customer")["Final_Sales"].sum().sort_values(ascending=False)

Customer
Frank       1425.0
Alice       1140.0
Isabella     990.0
Charlie      950.0
Bob          720.0
Henry        700.0
Emma         552.5
Grace        400.0
Jack         332.5
David        300.0
Name: Final_Sales, dtype: float64

In [14]:
df.groupby("Category")["Final_Sales"].sum().sort_values(ascending=False)

Category
Electronics    4505.0
Furniture      1972.5
Clothing       1032.5
Name: Final_Sales, dtype: float64

In [15]:
high_value_orders = df[df["Final_Sales"] > 1000]

high_value_orders

   Order_ID Customer     Category  Sales  Quantity  Discount  Final_Sales
0       101    Alice  Electronics   1200         2       5.0       1140.0
5       106    Frank  Electronics   1500         2       5.0       1425.0